version: "3.8"
services: 
  WAS_hardware:
    image: hwangjeyeon/busstation_test1:0.8
    ports:
      - "8083:8083"
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod_hardware
    networks:
      - busstation_network

  WAS_web:
    image: hwangjeyeon/busstation_test1:0.8
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod_webpage
    networks:
      - busstation_network
      
  webServer:
    image: hwangjeyeon/nginx:0.6
    ports:
      - "80:80"
    networks:
      - busstation_network
    depends_on:
      - WAS_hardware
      - WAS_web

networks:
  busstation_network:
